project:
  type: website
  output-dir: docs 
  resources: 
    - files/

navbar:
  background: transparent
  collapse: true 

format:
  html:
    favicon: favicon.png 
    theme: cosmo
    css: styles.css
    include-in-header:
      - _includes/header.html