project:
  type: website

website:
  title: "County Health Open-source Project"
  navbar:
    background: transparent
    collapse: false
    left:
      - text: "County Health Snapshots"
        href: snapshots.qmd
      - text: "The CHR&R Archives"
        href: archives.qmd
      - text: "CHR&R Open-source Community"
        href: community.qmd
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme: default
    css: styles.css
    include-in-header:
      - _includes/header.html
    output-dir: _site
