project:
  type: website
  output-dir: docs 

navbar:
  background: transparent
  collapse: true 

format:
  html:
    favicon: choplogo_gpt.png 
    theme: cosmo
    css: styles.css
    include-in-header:
      - _includes/header.html